var countme=0;
var sponsorcount=0;
var paths=["Background/accenture_logo.jpg","Background/IBM_logo.png","Background/vodafone_qatar.png"];
var menu_state=0;
var puller=0;
var eventset=1;	

$(document).ready(function(e) {
	
	
	
	$.modal.defaults.closeClass="introskip";
	
	sponsorme();
    $("#home").mouseover(function(){
		//alert("GHELL");
		$("#home").css("color","#0CF");
		
	});
	$("#home").mouseout(function(){
		$("#home").css("color","#FFF");
		
	});
	
	$("#events").mouseover(function(){
		$("#events").css("color","#0CF");
		
	});
	$("#events").mouseout(function(){
		$("#events").css("color","#FFF");
		
	});
	
	$("#schedule").mouseover(function(){
		$("#schedule").css("color","#0CF");
		
	});
	$("#schedule").mouseout(function(){
		$("#schedule").css("color","#FFF");
		
	});
	
	$("#workshops").mouseover(function(){
		$("#workshops").css("color","#0CF");
		
	});
	$("#workshops").mouseout(function(){
		$("#workshops").css("color","#FFF");
		
	});
	
	$("#hospitality").mouseover(function(){
		$("#hospitality").css("color","#0CF");
		
	});
	$("#hospitality").mouseout(function(){
		$("#hospitality").css("color","#FFF");
		
	});
	$("#register").click(function(){
		 alert("Registration are not yet open");
		 //$("#registermodal").modal();
	});
	$("#register").mouseover(function(){
		$("#register").css("color","#0CF");
	});
	$("#register").mouseout(function(){
		$("#register").css("color","#FFF");
	});
	$("#sponsors").mouseover(function(){
		$("#sponsors").css("color","#0CF");
		
	});
	$("#sponsors").mouseout(function(){
		$("#sponsors").css("color","#FFF");
		
	});
	
	$("#contact").mouseover(function(){
		$("#contact").css("color","#0CF");
		
	});
	$("#contact").mouseout(function(){
		$("#contact").css("color","#FFF");
		
	});
	
	$("#button").mouseover(function(){
		$("#button").attr("src","Background/submit_over.png");
	});
	$("#button").mouseout(function(){
		$("#button").attr("src","Background/submit.png");
	});
	
	$("#opener").click(function(){
		
		if(puller==0){
			$("#login_div").animate({marginLeft:"0px"},500);
			$("#opener").attr("width",14);
			$("#opener").attr("height",62);
			$("#opener").attr("src","Background/push_up.png");
			puller=1;
		}
		else{
			$("#login_div").animate({marginLeft:"-227px"},500);
			$("#opener").attr("width",17);
			$("#opener").attr("height",63);
			$("#opener").attr("src","Background/pull_down.png");
			puller=0;
		}
	});
	
	$("#testme").click(function(){
		if(menu_state==0){
			$("#testme").animate({marginLeft:"0%"},500);
			$("#menu").attr("src","Background/cm.png");
			menu_state=1;
		}
		else{
			$("#testme").animate({marginLeft:"-100px"},500);
			$("#menu").attr("src","Background/om.png");
			menu_state=0;
		}
	});
	
	$("#n4").click(function(){
	$("#teaminsig").modal();
	});
	$("#contact").click(function(){
	$("#teaminsig").modal();
	});
	$("#hospitality").click(function(){
	$("#myhos").modal();
	});
		$("#h1").click(function(){
	$("#reachme").modal();
	});
	
	$("#events").click(function(){
		$("#eventsect").modal();
	});
	
	$("#cs").click(function(){
		$("#content").fadeOut(500,"",function(){
			if(eventset==0){
				$("#content").empty();
			}
			if(eventset==2){
				$("#civilevents").appendTo("#eventholder");
			}
			if(eventset==3){
				$("#chemicalevents").appendTo("#eventholder");
			}
			if(eventset==4){
				$("#ecevents").appendTo("#eventholder");
			}
			if(eventset==5){
				$("#eeevents").appendTo("#eventholder");
			}
			if(eventset==6){
				$("#mechevents").appendTo("#eventholder");
			}
			if(eventset==7){
				$("#isevents").appendTo("#eventholder");
			}
			if(eventset==8){
				$("#roboevents").appendTo("#eventholder");
			}
			if(eventset==9){
				$("#bizbevents").appendTo("#eventholder");
			}
			if(eventset==10){
				$("#contevents").appendTo("#eventholder");
			}
			if(eventset==11){
				$("#slevents").appendTo("#eventholder");
			}
			if(eventset==12){
				$("#gamevents").appendTo("#eventholder");
			}
			if(eventset==13){
				$("#createevents").appendTo("#eventholder");
			}
			if(eventset==14){
				$("#managementevents").appendTo("#eventholder");
			}
			eventset=1;
			$("#csevents").appendTo("#content");
			$("#csevents").css("display","inline");
		});
		$("#content").fadeIn(500,"","");
	});
	
	$("#civ").click(function(){
		$("#content").fadeOut(500,"",function(){
			if(eventset==0){
				$("#content").empty();
			}
			if(eventset==1){
				$("#csevents").appendTo("#eventholder");
			}
			if(eventset==3){
				$("#chemicalevents").appendTo("#eventholder");
			}
			if(eventset==4){
				$("#ecevents").appendTo("#eventholder");
			}
			if(eventset==5){
				$("#eeevents").appendTo("#eventholder");
			}
			if(eventset==6){
				$("#mechevents").appendTo("#eventholder");
			}
			if(eventset==7){
				$("#isevents").appendTo("#eventholder");
			}
			if(eventset==8){
				$("#roboevents").appendTo("#eventholder");
			}
			if(eventset==9){
				$("#bizbevents").appendTo("#eventholder");
			}
			if(eventset==10){
				$("#contevents").appendTo("#eventholder");
			}
			if(eventset==11){
				$("#slevents").appendTo("#eventholder");
			}
			if(eventset==12){
				$("#gamevents").appendTo("#eventholder");
			}
			if(eventset==13){
				$("#createevents").appendTo("#eventholder");
			}
			if(eventset==14){
				$("#managementevents").appendTo("#eventholder");
			}
			eventset=2;
			$("#civilevents").appendTo("#content");
			$("#civilevents").css("display","inline");
		});
		$("#content").fadeIn(500,"","");
	});
	
	$("#chem").click(function(){
		$("#content").fadeOut(500,"",function(){
			if(eventset==0){
				$("#content").empty();
			}
			if(eventset==1){
				$("#csevents").appendTo("#eventholder");
			}
			if(eventset==2){
				$("#civilevents").appendTo("#eventholder");
			}
			if(eventset==4){
				$("#ecevents").appendTo("#eventholder");
			}
			if(eventset==5){
				$("#eeevents").appendTo("#eventholder");
			}
			if(eventset==6){
				$("#mechevents").appendTo("#eventholder");
			}
			if(eventset==7){
				$("#isevents").appendTo("#eventholder");
			}
			if(eventset==8){
				$("#roboevents").appendTo("#eventholder");
			}
			if(eventset==9){
				$("#bizbevents").appendTo("#eventholder");
			}
			if(eventset==10){
				$("#contevents").appendTo("#eventholder");
			}
			if(eventset==11){
				$("#slevents").appendTo("#eventholder");
			}
			if(eventset==12){
				$("#gamevents").appendTo("#eventholder");
			}
			if(eventset==13){
				$("#createevents").appendTo("#eventholder");
			}
			if(eventset==14){
				$("#managementevents").appendTo("#eventholder");
			}
			eventset=3;
			$("#chemicalevents").appendTo("#content");
			$("#chemicalevents").css("display","inline");
		});
		$("#content").fadeIn(500,"","");
	});
	
	$("#ec").click(function(){
		$("#content").fadeOut(500,"",function(){
			if(eventset==0){
				$("#content").empty();
			}
			if(eventset==1){
				$("#csevents").appendTo("#eventholder");
			}
			if(eventset==2){
				$("#civilevents").appendTo("#eventholder");
			}
			if(eventset==3){
				$("#chemicalevents").appendTo("#eventholder");
			}
			if(eventset==5){
				$("#eeevents").appendTo("#eventholder");
			}
			if(eventset==6){
				$("#mechevents").appendTo("#eventholder");
			}
			if(eventset==7){
				$("#isevents").appendTo("#eventholder");
			}
			if(eventset==8){
				$("#roboevents").appendTo("#eventholder");
			}
			if(eventset==9){
				$("#bizbevents").appendTo("#eventholder");
			}
			if(eventset==10){
				$("#contevents").appendTo("#eventholder");
			}
			if(eventset==11){
				$("#slevents").appendTo("#eventholder");
			}
			if(eventset==12){
				$("#gamevents").appendTo("#eventholder");
			}
			if(eventset==13){
				$("#createevents").appendTo("#eventholder");
			}
			if(eventset==14){
				$("#managementevents").appendTo("#eventholder");
			}
			eventset=4;
			$("#ecevents").appendTo("#content");
			$("#ecevents").css("display","inline");
		});
		$("#content").fadeIn(500,"","");
	});
	
	$("#ee").click(function(){
		$("#content").fadeOut(500,"",function(){
			if(eventset==0){
				$("#content").empty();
			}
			if(eventset==1){
				$("#csevents").appendTo("#eventholder");
			}
			if(eventset==2){
				$("#civilevents").appendTo("#eventholder");
			}
			if(eventset==3){
				$("#chemicalevents").appendTo("#eventholder");
			}
			if(eventset==4){
				$("#ecevents").appendTo("#eventholder");
			}
			if(eventset==6){
				$("#mechevents").appendTo("#eventholder");
			}
			if(eventset==7){
				$("#isevents").appendTo("#eventholder");
			}
			if(eventset==8){
				$("#roboevents").appendTo("#eventholder");
			}
			if(eventset==9){
				$("#bizbevents").appendTo("#eventholder");
			}
			if(eventset==10){
				$("#contevents").appendTo("#eventholder");
			}
			if(eventset==11){
				$("#slevents").appendTo("#eventholder");
			}
			if(eventset==12){
				$("#gamevents").appendTo("#eventholder");
			}
			if(eventset==13){
				$("#createevents").appendTo("#eventholder");
			}
			if(eventset==14){
				$("#managementevents").appendTo("#eventholder");
			}
			eventset=5;
			$("#eeevents").appendTo("#content");
			$("#eeevents").css("display","inline");
		});
		$("#content").fadeIn(500,"","");
	});
	
	$("#mech").click(function(){
		$("#content").fadeOut(500,"",function(){
			if(eventset==0){
				$("#content").empty();
			}
			if(eventset==1){
				$("#csevents").appendTo("#eventholder");
			}
			if(eventset==2){
				$("#civilevents").appendTo("#eventholder");
			}
			if(eventset==3){
				$("#chemicalevents").appendTo("#eventholder");
			}
			if(eventset==4){
				$("#ecevents").appendTo("#eventholder");
			}
			if(eventset==5){
				$("#eeevents").appendTo("#eventholder");
			}
			if(eventset==7){
				$("#isevents").appendTo("#eventholder");
			}
			if(eventset==8){
				$("#roboevents").appendTo("#eventholder");
			}
			if(eventset==9){
				$("#bizbevents").appendTo("#eventholder");
			}
			if(eventset==10){
				$("#contevents").appendTo("#eventholder");
			}
			if(eventset==11){
				$("#slevents").appendTo("#eventholder");
			}
			if(eventset==12){
				$("#gamevents").appendTo("#eventholder");
			}
			if(eventset==13){
				$("#createevents").appendTo("#eventholder");
			}
			if(eventset==14){
				$("#managementevents").appendTo("#eventholder");
			}
			eventset=6;
			$("#mechevents").appendTo("#content");
			$("#mechevents").css("display","inline");
		});
		$("#content").fadeIn(500,"","");
	});
	
	$("#is").click(function(){
		$("#content").fadeOut(500,"",function(){
			if(eventset==0){
				$("#content").empty();
			}
			if(eventset==1){
				$("#csevents").appendTo("#eventholder");
			}
			if(eventset==2){
				$("#civilevents").appendTo("#eventholder");
			}
			if(eventset==3){
				$("#chemicalevents").appendTo("#eventholder");
			}
			if(eventset==4){
				$("#ecevents").appendTo("#eventholder");
			}
			if(eventset==5){
				$("#eeevents").appendTo("#eventholder");
			}
			if(eventset==6){
				$("#mechevents").appendTo("#eventholder");
			}
			if(eventset==8){
				$("#roboevents").appendTo("#eventholder");
			}
			if(eventset==9){
				$("#bizbevents").appendTo("#eventholder");
			}
			if(eventset==10){
				$("#contevents").appendTo("#eventholder");
			}
			if(eventset==11){
				$("#slevents").appendTo("#eventholder");
			}
			if(eventset==12){
				$("#gamevents").appendTo("#eventholder");
			}
			if(eventset==13){
				$("#createevents").appendTo("#eventholder");
			}
			if(eventset==14){
				$("#managementevents").appendTo("#eventholder");
			}
			eventset=7;
			$("#isevents").appendTo("#content");
			$("#isevents").css("display","inline");
		});
		$("#content").fadeIn(500,"","");
	});
	
	$("#robo").click(function(){
		$("#content").fadeOut(500,"",function(){
			if(eventset==0){
				$("#content").empty();
			}
			if(eventset==1){
				$("#csevents").appendTo("#eventholder");
			}
			if(eventset==2){
				$("#civilevents").appendTo("#eventholder");
			}
			if(eventset==3){
				$("#chemicalevents").appendTo("#eventholder");
			}
			if(eventset==4){
				$("#ecevents").appendTo("#eventholder");
			}
			if(eventset==5){
				$("#eeevents").appendTo("#eventholder");
			}
			if(eventset==6){
				$("#mechevents").appendTo("#eventholder");
			}
			if(eventset==7){
				$("#isevents").appendTo("#eventholder");
			}
			if(eventset==9){
				$("#bizbevents").appendTo("#eventholder");
			}
			if(eventset==10){
				$("#contevents").appendTo("#eventholder");
			}
			if(eventset==11){
				$("#slevents").appendTo("#eventholder");
			}
			if(eventset==12){
				$("#gamevents").appendTo("#eventholder");
			}
			if(eventset==13){
				$("#createevents").appendTo("#eventholder");
			}
			if(eventset==14){
				$("#managementevents").appendTo("#eventholder");
			}
			eventset=8;
			$("#roboevents").appendTo("#content");
			$("#roboevents").css("display","inline");
		});
		$("#content").fadeIn(500,"","");
	});
	
	$("#bizb").click(function(){
		$("#content").fadeOut(500,"",function(){
			if(eventset==0){
				$("#content").empty();
			}
			if(eventset==1){
				$("#csevents").appendTo("#eventholder");
			}
			if(eventset==2){
				$("#civilevents").appendTo("#eventholder");
			}
			if(eventset==3){
				$("#chemicalevents").appendTo("#eventholder");
			}
			if(eventset==4){
				$("#ecevents").appendTo("#eventholder");
			}
			if(eventset==5){
				$("#eeevents").appendTo("#eventholder");
			}
			if(eventset==6){
				$("#mechevents").appendTo("#eventholder");
			}
			if(eventset==7){
				$("#isevents").appendTo("#eventholder");
			}
			if(eventset==8){
				$("#roboevents").appendTo("#eventholder");
			}
			if(eventset==10){
				$("#contevents").appendTo("#eventholder");
			}
			if(eventset==11){
				$("#slevents").appendTo("#eventholder");
			}
			if(eventset==12){
				$("#gamevents").appendTo("#eventholder");
			}
			if(eventset==13){
				$("#createevents").appendTo("#eventholder");
			}
			if(eventset==14){
				$("#managementevents").appendTo("#eventholder");
			}
			eventset=9;
			$("#bizbevents").appendTo("#content");
			$("#bizbevents").css("display","inline");
		});
		$("#content").fadeIn(500,"","");
	});
	
	$("#cont").click(function(){
		$("#content").fadeOut(500,"",function(){
			if(eventset==0){
				$("#content").empty();
			}
			if(eventset==1){
				$("#csevents").appendTo("#eventholder");
			}
			if(eventset==2){
				$("#civilevents").appendTo("#eventholder");
			}
			if(eventset==3){
				$("#chemicalevents").appendTo("#eventholder");
			}
			if(eventset==4){
				$("#ecevents").appendTo("#eventholder");
			}
			if(eventset==5){
				$("#eeevents").appendTo("#eventholder");
			}
			if(eventset==6){
				$("#mechevents").appendTo("#eventholder");
			}
			if(eventset==7){
				$("#isevents").appendTo("#eventholder");
			}
			if(eventset==8){
				$("#roboevents").appendTo("#eventholder");
			}
			if(eventset==9){
				$("#bizbevents").appendTo("#eventholder");
			}
			if(eventset==11){
				$("#slevents").appendTo("#eventholder");
			}
			if(eventset==12){
				$("#gamevents").appendTo("#eventholder");
			}
			if(eventset==13){
				$("#createevents").appendTo("#eventholder");
			}
			if(eventset==14){
				$("#managementevents").appendTo("#eventholder");
			}
			eventset=10;
			$("#contevents").appendTo("#content");
			$("#contevents").css("display","inline");
		});
		$("#content").fadeIn(500,"","");
	});
	
	$("#sl").click(function(){
		$("#content").fadeOut(500,"",function(){
			if(eventset==0){
				$("#content").empty();
			}
			if(eventset==1){
				$("#csevents").appendTo("#eventholder");
			}
			if(eventset==2){
				$("#civilevents").appendTo("#eventholder");
			}
			if(eventset==3){
				$("#chemicalevents").appendTo("#eventholder");
			}
			if(eventset==4){
				$("#ecevents").appendTo("#eventholder");
			}
			if(eventset==5){
				$("#eeevents").appendTo("#eventholder");
			}
			if(eventset==6){
				$("#mechevents").appendTo("#eventholder");
			}
			if(eventset==7){
				$("#isevents").appendTo("#eventholder");
			}
			if(eventset==8){
				$("#roboevents").appendTo("#eventholder");
			}
			if(eventset==9){
				$("#bizbevents").appendTo("#eventholder");
			}
			if(eventset==10){
				$("#contevents").appendTo("#eventholder");
			}
			if(eventset==12){
				$("#gamevents").appendTo("#eventholder");
			}
			if(eventset==13){
				$("#createevents").appendTo("#eventholder");
			}
			if(eventset==14){
				$("#managementevents").appendTo("#eventholder");
			}
			eventset=11;
			$("#slevents").appendTo("#content");
			$("#slevents").css("display","inline");
		});
		$("#content").fadeIn(500,"","");
	});
	
	$("#gam").click(function(){
		$("#content").fadeOut(500,"",function(){
			if(eventset==0){
				$("#content").empty();
			}
			if(eventset==1){
				$("#csevents").appendTo("#eventholder");
			}
			if(eventset==2){
				$("#civilevents").appendTo("#eventholder");
			}
			if(eventset==3){
				$("#chemicalevents").appendTo("#eventholder");
			}
			if(eventset==4){
				$("#ecevents").appendTo("#eventholder");
			}
			if(eventset==5){
				$("#eeevents").appendTo("#eventholder");
			}
			if(eventset==6){
				$("#mechevents").appendTo("#eventholder");
			}
			if(eventset==7){
				$("#isevents").appendTo("#eventholder");
			}
			if(eventset==8){
				$("#roboevents").appendTo("#eventholder");
			}
			if(eventset==9){
				$("#bizbevents").appendTo("#eventholder");
			}
			if(eventset==10){
				$("#contevents").appendTo("#eventholder");
			}
			if(eventset==11){
				$("#slevents").appendTo("#eventholder");
			}
			if(eventset==13){
				$("#createevents").appendTo("#eventholder");
			}
			if(eventset==14){
				$("#managementevents").appendTo("#eventholder");
			}
			eventset=12;
			$("#gamevents").appendTo("#content");
			$("#gamevents").css("display","inline");
		});
		$("#content").fadeIn(500,"","");
	});
	
	$("#create").click(function(){
		$("#content").fadeOut(500,"",function(){
			if(eventset==0){
				$("#content").empty();
			}
			if(eventset==1){
				$("#csevents").appendTo("#eventholder");
			}
			if(eventset==2){
				$("#civilevents").appendTo("#eventholder");
			}
			if(eventset==3){
				$("#chemicalevents").appendTo("#eventholder");
			}
			if(eventset==4){
				$("#ecevents").appendTo("#eventholder");
			}
			if(eventset==5){
				$("#eeevents").appendTo("#eventholder");
			}
			if(eventset==6){
				$("#mechevents").appendTo("#eventholder");
			}
			if(eventset==7){
				$("#isevents").appendTo("#eventholder");
			}
			if(eventset==8){
				$("#roboevents").appendTo("#eventholder");
			}
			if(eventset==9){
				$("#bizbevents").appendTo("#eventholder");
			}
			if(eventset==10){
				$("#contevents").appendTo("#eventholder");
			}
			if(eventset==11){
				$("#slevents").appendTo("#eventholder");
			}
			if(eventset==12){
				$("#gamevents").appendTo("#eventholder");
			}
			if(eventset==14){
				$("#managementevents").appendTo("#eventholder");
			}
			eventset=13;
			$("#createevents").appendTo("#content");
			$("#createevents").css("display","inline");
		});
		$("#content").fadeIn(500,"","");
	});
	$("#manage").click(function(){
		$("#content").fadeOut(500,"",function(){
			if(eventset==0){
				$("#content").empty();
			}
			if(eventset==1){
				$("#csevents").appendTo("#eventholder");
			}
			if(eventset==2){
				$("#civilevents").appendTo("#eventholder");
			}
			if(eventset==3){
				$("#chemicalevents").appendTo("#eventholder");
			}
			if(eventset==4){
				$("#ecevents").appendTo("#eventholder");
			}
			if(eventset==5){
				$("#eeevents").appendTo("#eventholder");
			}
			if(eventset==6){
				$("#mechevents").appendTo("#eventholder");
			}
			if(eventset==7){
				$("#isevents").appendTo("#eventholder");
			}
			if(eventset==8){
				$("#roboevents").appendTo("#eventholder");
			}
			if(eventset==9){
				$("#bizbevents").appendTo("#eventholder");
			}
			if(eventset==10){
				$("#contevents").appendTo("#eventholder");
			}
			if(eventset==11){
				$("#slevents").appendTo("#eventholder");
			}
			if(eventset==12){
				$("#gamevents").appendTo("#eventholder");
			}
			if(eventset==13){
				$("#createvents").appendTo("#eventholder");
			}
			eventset=14;
			$("#managementevents").appendTo("#content");
			$("#managementevents").css("display","inline");
		});
		$("#content").fadeIn(500,"","");
	});
	
	$("#cspptevent").click(function(){
		$("#csppt").modal();
	});
	$("#csnightoutevent").click(function(){
		$("#csnightout").modal();
	});
	$("#csautomataevent").click(function(){
		$("#csautomata").modal();
	});
	$("#csepuzzleevent").click(function(){
		$("#csepuzzle").modal();
	});
	$("#csedesign").click(function(){
		$("#csedesignevent").modal();
	});
	$("#chempptevent").click(function(){
		$("#chemppt").modal();
	});
	$("#chemreactionevent").click(function(){
		$("#chemreaction").modal();
	});
	$("#chemposterevent").click(function(){
		$("#chemposter").modal();
	});
	$("#chemicalquiz").click(function(){
		$("#chemquiz").modal();
	});
	$("#chemidp").click(function(){
		$("#chemidpevent").modal();
	});
	$("#chemtrouble").click(function(){
		$("#chemtroubleevent").modal();
	});
	$("#chemmodel").click(function(){
		$("#chemmodelevent").modal();
	});
	$("#civilpptevent").click(function(){
		$("#civilppts").modal();
	});
	$("#civilarchitexevent").click(function(){
		$("#civilarchitex").modal();
	});
	$("#civilplirisevent").click(function(){
		$("#civilpliris").modal();
	});
	$("#civilwalkevent").click(function(){
		$("#civilwalk").modal();
	});
	$("#civilmindtrapevent").click(function(){
		$("#civilmindtrap").modal();
	});
	$("#encpptevent").click(function(){
		$("#encppt").modal();
	});
	$("#enctroubleevent").click(function(){
		$("#enctroubleshoot").modal();
	});
	$("#encbrains").click(function(){
		$("#encbrainstorm").modal();
	});
	$("#encquiz").click(function(){
		$("#encquizevent").modal();
	});
	$("#encantenna").click(function(){
		$("#encantennaevent").modal();
	});
	$("#encrobot").click(function(){
		$("#encrobotevent").modal();
	});
	$("#enepptevent").click(function(){
		$("#eneppt").modal();
	});
	$("#enetroubleevent").click(function(){
		$("#enetrouble").modal();
	});
	$("#mechpptevent").click(function(){
		$("#mechppt").modal();
	});
	$("#mechjunks").click(function(){
		$("#mechjunkevent").modal();
	});
	$("#mechoverevent").click(function(){
		$("#mechover").modal();
	});
	$("#mechauto").click(function(){
		$("#mechquizevent").modal();
	});
	$("#mechnights").click(function(){
		$("#mechnightevent").modal();
	});
	$("#mechesd").click(function(){
		$("#mechesdevent").modal();
	});
	$("#isepptevent").click(function(){
		$("#info_scippt").modal();
	});
	$("#iseembed").click(function(){
		$("#iseembedevent").modal();
	});
	$("#isecode").click(function(){
		$("#isecodeevent").modal();
	});
	$("#isequiz").click(function(){
		$("#isequizevent").modal();
	});
	$("#death").click(function(){
		$("#deathevent").modal();
	});
	$("#polo").click(function(){
		$("#poloevent").modal();
	});
	$("#bizmunevent").click(function(){
		$("#bizmun").modal();
	});
	$("#bizexpevent").click(function(){
		$("#bizexp").modal();
	});
	$("#bizboardevent").click(function(){
		$("#bizboard").modal();
	});
	
	$("#slad").click(function(){
		$("#ladders").modal();
	});
	$("#tp").click(function(){
		$("#deathevent").modal();
	});
	$("#rc").click(function(){
		$("#poloevent").modal();
	});
	$("#sur").click(function(){
		$("#rcevent").modal();
	});
	
});

	
	
function sponsorme(){
	/*$("#spons").fadeOut(200,function(){
		$("#spons").html("<img src='"+paths[sponsorcount]+"'/>");
	});
	$("#spons").fadeIn(200,function(){});
	sponsorcount++;
	if(sponsorcount==3){
		sponsorcount=0;
	}
	window.setTimeout("sponsorme()",5000);*/
}

// JavaScript Document